-- Barcode → product mapping for USB-scanner billing.
-- Maps a scanned barcode to one of your medicine names; the rest of billing
-- (batch/MRP/rate/GST) is then looked up by name exactly as before.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard → SQL Editor → New query
-- → paste → Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.barcodes (
    id           bigint generated by default as identity primary key,
    user_id      text not null,
    barcode      text not null,
    product_name text not null default '',
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

-- One product per barcode per shop (lets us upsert-update the name on conflict).
create unique index if not exists barcodes_user_code_uniq
    on public.barcodes (user_id, barcode);

-- Same tenant isolation as every other data table: browsers get the CRUD grant,
-- RLS restricts every row to the caller's own tenant via current_tenant().
grant select, insert, update, delete on public.barcodes to anon, authenticated;

alter table public.barcodes enable row level security;

drop policy if exists tenant_rw on public.barcodes;
create policy tenant_rw on public.barcodes
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
